name: documentation
on:
  push:
    branches:
      - main
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: conda env update --name base --file conda.yml
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - run: poetry install
      - run: mkdocs gh-deploy --force
