name: documentation
on:
  push:
    branches:
      - main
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: conda install --file conda.yml
      - run: poetry install
      - run: mkdocs gh-deploy --force
