name: documentation
on:
  push:
    branches:
      - main
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: changelog39
          environment-file: conda.yml
          python-version: 3.9
          auto-activate-base: false
      - run: conda info
      - run: conda activate changelog39
      - run: conda info
#       - name: Install Poetry
#         uses: snok/install-poetry@v1
      - run: poetry install
      - run: mkdocs gh-deploy --force
