name: documentation
on:
  push:
    branches:
      - main
jobs:
  gh-pages:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0} # needed to share shell profile between steps https://github.community/t/how-to-share-shell-profile-between-steps-or-how-to-use-nvm-rvm-in-steps/16398
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: changelog39
          environment-file: conda.yml
          python-version: 3.9
          auto-activate-base: false
      - run: poetry install
      - run: mkdocs gh-deploy --force
